import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "@/hooks/use-toast";

export interface LabInvoiceRow {
  id: string;
  invoice_number: string;
  clinic_code: string;
  clinic_doctor_name: string;
  patient_name: string;
  lab_case_id: string | null;
  invoice_date: string;
  subtotal: number;
  discount: number;
  total_amount: number;
  amount_paid: number;
  deposit_amount: number;
  status: string;
  notes: string;
  created_at: string;
  updated_at: string;
}

export function useLabInvoices() {
  return useQuery({
    queryKey: ["lab_invoices"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("lab_invoices")
        .select("*")
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as unknown as LabInvoiceRow[];
    },
  });
}

export function useLabInvoiceStats() {
  const { data: invoices = [], isLoading } = useLabInvoices();
  
  const totalRevenue = invoices.reduce((s, i) => s + Number(i.total_amount), 0);
  const totalPaid = invoices.reduce((s, i) => s + Number(i.amount_paid), 0);
  const totalOutstanding = totalRevenue - totalPaid;
  const unpaidCount = invoices.filter((i) => i.status !== "paid").length;

  return { invoices, totalRevenue, totalPaid, totalOutstanding, unpaidCount, isLoading };
}

export function useCreateLabInvoice() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async (invoice: {
      clinic_code?: string;
      clinic_doctor_name?: string;
      patient_name?: string;
      lab_case_id?: string;
      subtotal: number;
      discount?: number;
      amount_paid?: number;
      deposit_amount?: number;
      notes?: string;
    }) => {
      const disc = invoice.discount || 0;
      const total = Math.max(invoice.subtotal - disc, 0);
      const deposit = Math.min(invoice.deposit_amount || 0, total);
      const paid = Math.min(invoice.amount_paid || deposit, total);
      const status = paid >= total ? "paid" : paid > 0 ? "partial" : "unpaid";

      const { data, error } = await supabase
        .from("lab_invoices")
        .insert({
          invoice_number: "", // auto-generated by trigger
          clinic_code: invoice.clinic_code || "",
          clinic_doctor_name: invoice.clinic_doctor_name || "",
          patient_name: invoice.patient_name || "",
          lab_case_id: invoice.lab_case_id || null,
          subtotal: invoice.subtotal,
          discount: disc,
          total_amount: total,
          amount_paid: paid,
          deposit_amount: deposit,
          status,
          notes: invoice.notes || "",
        })
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["lab_invoices"] });
      toast({ title: "Lab invoice created" });
    },
    onError: (e) => {
      toast({ title: "Error", description: e.message, variant: "destructive" });
    },
  });
}

export function useUpdateLabInvoice() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, ...updates }: {
      id: string;
      amount_paid?: number;
      status?: string;
      notes?: string;
    }) => {
      const { data, error } = await supabase
        .from("lab_invoices")
        .update(updates)
        .eq("id", id)
        .select()
        .single();
      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["lab_invoices"] });
      toast({ title: "Lab invoice updated" });
    },
    onError: (e) => {
      toast({ title: "Error", description: e.message, variant: "destructive" });
    },
  });
}
